### ISSUE TITLE
Consider also running cargo fmt?

### ISSUE THREAD

**Issue by Armavica** [KarelPeeters/board-game-rs#4]
To standardize the coding style, maybe it could also be a good idea to run `cargo fmt` manually or automatically?

**Comment by KarelPeeters** [comment]
Yeah you're right, I ran it on all exiting code and added it to the CI checks. It's arguably worse then the intelij-rust autoformatter (see below), but at least it's consistent for everyone.

https://github.com/KarelPeeters/board-game-rs/commit/ace8d9961d922e193ae7a8f8f41c84d431d50b2b#diff-497e591de72dcf8fa70d1f61bfa4e5d2d7eae9d3f0b811bc1e5ea454c8175dbfR53-R70
